from __future__ import annotations

from typing import Protocol

from .entities import ClassificationResult, Job, JobRecord, JobStatus


class QueuePort(Protocol):
    async def publish(self, stage: str, job_id: str) -> None: ...
    async def consume(self, stage: str) -> str: ...


class JobStorePort(Protocol):
    def create(self, job: Job) -> JobRecord: ...
    def get(self, job_id: str) -> JobRecord | None: ...
    def update_status(self, job_id: str, status: JobStatus, error: str | None = None) -> JobRecord: ...
    def save_result(self, job_id: str, result: ClassificationResult, artifacts: dict[str, str]) -> JobRecord: ...


class ClassifierPort(Protocol):
    def classify_image(self, image_path: str, criteria: int = 0) -> ClassificationResult: ...
    def classify_video(self, video_path: str, criteria: int = 0) -> ClassificationResult: ...


class StoragePort(Protocol):
    def ensure_job_dir(self, job_id: str) -> str: ...
    def download(self, url: str, dst_path: str) -> str: ...
    def upload(self, src_path: str, dst_name: str) -> str: ...


class CallbackPort(Protocol):
    def send(self, callback_url: str, payload: dict) -> None: ...


class VideoPort(Protocol):
    def extract_keyframes(self, video_path: str, output_dir: str, frame_step: int) -> list[str]: ...
